### ISSUE TITLE
Pushing flows failing

### ISSUE THREAD

**Issue by hardillb** [1PhoenixM/avior-service#1]
Hi,

I'm playing with Openvswitch, floodlight and avior but I don't seam to be able to push a flow to the controller. When ever I hit push I see something similar to this on the console:

POSTED DATA: {"switch":"00:00:00:00:00:aa:00:00","actions":"output=all"}

{"switch":"00:00:00:00:00:aa:00:00","actions":"output=all"}
STATUS: 404
HEADERS: {"content-type":"application/json","date":"Thu, 12 Mar 2015 14:58:30 GMT","accept-ranges":"bytes","server":"Restlet-Framework/2.2m3","connection":"keep-alive","transfer-encoding":"chunked"}
BODY: {"code":404,"description":"The server has not found anything matching the request URI","reasonPhrase":"Not Found","throwable":null,"uri":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5","globalError":false,"redirection":false,"recoverableError":false,"success":false,"serverError":false,"connectorError":false,"clientError":true,"informational":false,"error":true}

I'm using the git head version of avior and the latest build of floodlight

**Comment by 1PhoenixM** [comment]
OK, thanks for finding this problem...

The native Floodlight API changed the name of its flow calls. That's why you were receiving a 404 error in the debug data. The old name no longer existed.

I have corrected this with the new name. Please pull and run the new version, and comment back if it now works or not

**Comment by hardillb** [comment]
That seams to have fixed it

Thanks

**Comment by hardillb** [comment]
Sorry, while the 404s have stopped I think there is still an issue.
The Flow Editor is missing the ingress/egress port and name entries look to be missing and there is no Port info showing on the right hand side (under the switches list).

![screenshot from 2015-03-13 14 09 22](https://cloud.githubusercontent.com/assets/1800845/6639811/9a864c62-c98a-11e4-9d9a-f4c79b527d54.png)

The chrome console implies the "Port" field is missing from some data structure. I'm poking round the code trying to work it out, but it may be immediately obvious to you.

```
Uncaught ReferenceError: Ports is not definedVM707:1 
(anonymous function)switchDetail.js:185 
Backbone.View.extend.displayPortsswitchDetail.js:123 
(anonymous function)lodash.min.js:31 
(anonymous function)lodash.min.js:20 
wtswitchDetail.js:118 
Backbone.View.extend.renderfrontpage.js:145 
syncCompletebackbone.min.js:1 
cbackbone.min.js:1 
a.Events.triggerbackbone.min.js:1 
t.successjquery.min.js:4 
cjquery.min.js:4 
p.fireWithjquery.min.js:6 
kjquery.min.js:6 r
```

**Comment by 1PhoenixM** [comment]
Once again, Floodlight's new API is the culprit...

Did a bit of rewriting with the new API names and such, so those problems should be fixed now. You should be able to get the Ports list and it will render. I'll fix the action and match renderings shortly. Thanks
